version: "3.8"
services:
  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Evita que los node_modules de tu máquina sobrescriban los del contenedor
    environment:
      - CHOKIDAR_USEPOLLING=true # Para detectar cambios en archivos dentro del contenedor

  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules  # Evita conflictos con node_modules
      - ./backend/src:/app/src  # Sincroniza solo la carpeta src
    environment:
      - CHOKIDAR_USEPOLLING=true  # Para que detecte cambios en el código
