services:
  db:
    image: postgres:15
    container_name: sistema-consultorio-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: consultorio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: sistema-consultorio-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: consultorio
      DB_PORT: 5432
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./frontend/sistema-consultorio
    container_name: sistema-consultorio-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend/sistema-consultorio:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
